name: Java CI with Gradle

on:
  push:
    branches:
      - '**'          # запуск на любой ветке
  pull_request:
    branches:
      - '**'          # запуск на любой PR

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [8, 11]   # тестируем на JDK 8 и 11

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin   # официальный дистрибутив Adoptium/Temurin

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and test with Gradle
        run: ./gradlew clean test
